# Generated by Django 4.0.3 on 2022-03-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_contactmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
